# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import datetime
from typing import Optional

import pydantic


class Tweet(pydantic.BaseModel):
    id: int
    created_at: datetime.datetime
    tweeted_at: datetime.datetime
    text: str
    replies: int
    retweets: int
    likes: int
    views: int
    user_handle: str
    parent_id: Optional[int]


class User(pydantic.BaseModel):
    handle: str
    created_at: datetime.datetime
    name: str
    description: Optional[str]
    following: int
    followers: int
